version: '3.8'

services:
  bot:
    build: .
    container_name: aiogram_bot
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1313
      POSTGRES_DB: tg_cards
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: